services:
    db:
      image: mysql
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: Centro
      volumes:
        - db_datos:/var/lib/mysql
      networks:
        red_backend:
          ipv4_address: 192.168.1.3
    
    backend:
      build:
        context: .
        dockerfile: servidorDocker
      container_name: backend
      depends_on:
        - db
      networks:
        red_backend:
          ipv4_address: 192.168.1.2
        red_frontend:
          ipv4_address: 192.168.2.2
      command: ["wait-for-it.sh", "192.168.1.3:3306", "--timeout=30", "--", "node", "app.js"]
    
    frontend:
      build:
        context: .
        dockerfile: frontendDocker
      container_name: frontend
      depends_on:
        - backend
      networks:
        red_frontend:
          ipv4_address: 192.168.2.3
      command: ["npm", "start"]
      ports:
        - "4200:4200"

    ftp:
      image: stilliard/pure-ftpd
      container_name: ftp
      networks:
        red_backend:
          ipv4_address: 192.168.1.4
      environment:
        FTP_USER_NAME: user
        FTP_USER_PASS: password
        FTP_USER_HOME: /home/user
      volumes:
        - ftp_data:/home/user

volumes:
  db_datos:
    driver: local
  ftp_data:
    driver: local

networks:
  red_backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

  red_frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
